require.config({
    baseUrl: "src",
    paths: {
        "aloha-editor":                 "bower_components/aloha-editor/",
        "jquery":                       "bower_components/jquery/dist/jquery",
        "jquery.browser":               "bower_components/jquery.browser/dist/jquery.browser",
        "logging":                      "bower_components/logging/src/logging",
        "mockup-parser":                "bower_components/mockup-core/js/parser",
        "mockup-patterns-base":         "bower_components/mockup-core/js/pattern",
        "pat-compat":                   "bower_components/patternslib/src/core/compat",
        "pat-jquery-ext":               "bower_components/patternslib/src/core/jquery-ext",
        "pat-logger":                   "bower_components/patternslib/src/core/logger",
        "pat-parser":                   "bower_components/patternslib/src/core/parser",
        "pat-registry":                 "bower_components/patternslib/src/core/registry",
        "pat-utils":                    "bower_components/patternslib/src/core/utils",
        "patterns":                     "bower_components/patternslib/bundle",

		// Aloha's patched jquery-ui
		"jqueryui":                     "bower_components/aloha-editor/src/lib/vendor/jquery-ui-1.9.0.custom-aloha",

		// For the repository browser
		"PubSub":                       "bower_components/aloha-editor/src/lib/vendor/pubsub/js/pubsub-unminified",
		"Class":                        "bower_components/aloha-editor/src/lib/vendor/class",
		"RepositoryBrowser":            "bower_components/aloha-editor/src/lib/vendor/repository-browser/js/repository-browser-unminified",
		"jstree":                       "bower_components/aloha-editor/src/lib/vendor/jquery.jstree",              // Mutates jquery
		"jqgrid":                       "bower_components/aloha-editor/src/lib/vendor/jquery.jqgrid",              // Mutates jquery
		"jquery-layout":                "bower_components/aloha-editor/src/lib/vendor/jquery.layout-1.3.0-rc29.14",     // Mutates jquery
		"jqgrid-locale-en":             "bower_components/aloha-editor/src/lib/vendor/grid.locale.en", // Mutates jqgrid
		"jqgrid-locale-de":             "bower_components/aloha-editor/src/lib/vendor/grid.locale.de", // Mutates jqgrid
		"repository-browser-i18n-de":   "bower_components/aloha-editor/src/lib/vendor/repository-browser/js/repository-browser-unminified",
		"repository-browser-i18n-en":   "bower_components/aloha-editor/src/lib/vendor/repository-browser/js/repository-browser-unminified",

		// Shortcuts for all common plugins
		"ui":                           "bower_components/aloha-editor/src/plugins/common/ui/lib",
		"ui/vendor":                    "bower_components/aloha-editor/src/plugins/common/ui/vendor",
		"ui/css":                       "bower_components/aloha-editor/src/plugins/common/ui/css",
		"ui/nls":                       "bower_components/aloha-editor/src/plugins/common/ui/nls",
		"ui/res":                       "bower_components/aloha-editor/src/plugins/common/ui/res",
		"link":                         "bower_components/aloha-editor/src/plugins/common/link/lib",
		"link/vendor":                  "bower_components/aloha-editor/src/plugins/common/link/vendor",
		"link/css":                     "bower_components/aloha-editor/src/plugins/common/link/css",
		"link/nls":                     "bower_components/aloha-editor/src/plugins/common/link/nls",
		"link/res":                     "bower_components/aloha-editor/src/plugins/common/link/res",
		"table":                        "bower_components/aloha-editor/src/plugins/common/table/lib",
		"table/vendor":                 "bower_components/aloha-editor/src/plugins/common/table/vendor",
		"table/css":                    "bower_components/aloha-editor/src/plugins/common/table/css",
		"table/nls":                    "bower_components/aloha-editor/src/plugins/common/table/nls",
		"table/res":                    "bower_components/aloha-editor/src/plugins/common/table/res",
		"list":                         "bower_components/aloha-editor/src/plugins/common/list/lib",
		"list/vendor":                  "bower_components/aloha-editor/src/plugins/common/list/vendor",
		"list/css":                     "bower_components/aloha-editor/src/plugins/common/list/css",
		"list/nls":                     "bower_components/aloha-editor/src/plugins/common/list/nls",
		"list/res":                     "bower_components/aloha-editor/src/plugins/common/list/res",
		"image":                        "bower_components/aloha-editor/src/plugins/common/image/lib",
		"image/vendor":                 "bower_components/aloha-editor/src/plugins/common/image/vendor",
		"image/css":                    "bower_components/aloha-editor/src/plugins/common/image/css",
		"image/nls":                    "bower_components/aloha-editor/src/plugins/common/image/nls",
		"image/res":                    "bower_components/aloha-editor/src/plugins/common/image/res",
		"highlighteditables":           "bower_components/aloha-editor/src/plugins/common/highlighteditables/lib",
		"highlighteditables/vendor":    "bower_components/aloha-editor/src/plugins/common/highlighteditables/vendor",
		"highlighteditables/css":       "bower_components/aloha-editor/src/plugins/common/highlighteditables/css",
		"highlighteditables/nls":       "bower_components/aloha-editor/src/plugins/common/highlighteditables/nls",
		"highlighteditables/res":       "bower_components/aloha-editor/src/plugins/common/highlighteditables/res",
		"format":                       "bower_components/aloha-editor/src/plugins/common/format/lib",
		"format/vendor":                "bower_components/aloha-editor/src/plugins/common/format/vendor",
		"format/css":                   "bower_components/aloha-editor/src/plugins/common/format/css",
		"format/nls":                   "bower_components/aloha-editor/src/plugins/common/format/nls",
		"format/res":                   "bower_components/aloha-editor/src/plugins/common/format/res",
		"dom-to-xhtml":                 "bower_components/aloha-editor/src/plugins/common/dom-to-xhtml/lib",
		"dom-to-xhtml/vendor":          "bower_components/aloha-editor/src/plugins/common/dom-to-xhtml/vendor",
		"dom-to-xhtml/css":             "bower_components/aloha-editor/src/plugins/common/dom-to-xhtml/css",
		"dom-to-xhtml/nls":             "bower_components/aloha-editor/src/plugins/common/dom-to-xhtml/nls",
		"dom-to-xhtml/res":             "bower_components/aloha-editor/src/plugins/common/dom-to-xhtml/res",
		"contenthandler":               "bower_components/aloha-editor/src/plugins/common/contenthandler/lib",
		"contenthandler/vendor":        "bower_components/aloha-editor/src/plugins/common/contenthandler/vendor",
		"contenthandler/css":           "bower_components/aloha-editor/src/plugins/common/contenthandler/css",
		"contenthandler/nls":           "bower_components/aloha-editor/src/plugins/common/contenthandler/nls",
		"contenthandler/res":           "bower_components/aloha-editor/src/plugins/common/contenthandler/res",
		"characterpicker":              "bower_components/aloha-editor/src/plugins/common/characterpicker/lib",
		"characterpicker/vendor":       "bower_components/aloha-editor/src/plugins/common/characterpicker/vendor",
		"characterpicker/css":          "bower_components/aloha-editor/src/plugins/common/characterpicker/css",
		"characterpicker/nls":          "bower_components/aloha-editor/src/plugins/common/characterpicker/nls",
		"characterpicker/res":          "bower_components/aloha-editor/src/plugins/common/characterpicker/res",
		"commands":                     "bower_components/aloha-editor/src/plugins/common/commands/lib",
		"commands/vendor":              "bower_components/aloha-editor/src/plugins/common/commands/vendor",
		"commands/css":                 "bower_components/aloha-editor/src/plugins/common/commands/css",
		"commands/nls":                 "bower_components/aloha-editor/src/plugins/common/commands/nls",
		"commands/res":                 "bower_components/aloha-editor/src/plugins/common/commands/res",
		"align":                        "bower_components/aloha-editor/src/plugins/common/align/lib",
		"align/vendor":                 "bower_components/aloha-editor/src/plugins/common/align/vendor",
		"align/css":                    "bower_components/aloha-editor/src/plugins/common/align/css",
		"align/nls":                    "bower_components/aloha-editor/src/plugins/common/align/nls",
		"align/res":                    "bower_components/aloha-editor/src/plugins/common/align/res",
		"abbr":                         "bower_components/aloha-editor/src/plugins/common/abbr/lib",
		"abbr/vendor":                  "bower_components/aloha-editor/src/plugins/common/abbr/vendor",
		"abbr/css":                     "bower_components/aloha-editor/src/plugins/common/abbr/css",
		"abbr/nls":                     "bower_components/aloha-editor/src/plugins/common/abbr/nls",
		"abbr/res":                     "bower_components/aloha-editor/src/plugins/common/abbr/res",
		"block":                        "bower_components/aloha-editor/src/plugins/common/block/lib",
		"block/vendor":                 "bower_components/aloha-editor/src/plugins/common/block/vendor",
		"block/css":                    "bower_components/aloha-editor/src/plugins/common/block/css",
		"block/nls":                    "bower_components/aloha-editor/src/plugins/common/block/nls",
		"block/res":                    "bower_components/aloha-editor/src/plugins/common/block/res",
		"horizontalruler":              "bower_components/aloha-editor/src/plugins/common/horizontalruler/lib",
		"horizontalruler/vendor":       "bower_components/aloha-editor/src/plugins/common/horizontalruler/vendor",
		"horizontalruler/css":          "bower_components/aloha-editor/src/plugins/common/horizontalruler/css",
		"horizontalruler/nls":          "bower_components/aloha-editor/src/plugins/common/horizontalruler/nls",
		"horizontalruler/res":          "bower_components/aloha-editor/src/plugins/common/horizontalruler/res",
		"undo":                         "bower_components/aloha-editor/src/plugins/common/undo/lib",
		"undo/vendor":                  "bower_components/aloha-editor/src/plugins/common/undo/vendor",
		"undo/css":                     "bower_components/aloha-editor/src/plugins/common/undo/css",
		"undo/nls":                     "bower_components/aloha-editor/src/plugins/common/undo/nls",
		"undo/res":                     "bower_components/aloha-editor/src/plugins/common/undo/res",
		"paste":                        "bower_components/aloha-editor/src/plugins/common/paste/lib",
		"paste/vendor":                 "bower_components/aloha-editor/src/plugins/common/paste/vendor",
		"paste/css":                    "bower_components/aloha-editor/src/plugins/common/paste/css",
		"paste/nls":                    "bower_components/aloha-editor/src/plugins/common/paste/nls",
		"paste/res":                    "bower_components/aloha-editor/src/plugins/common/paste/res",
		"autoparagraph":                "bower_components/aloha-editor/src/plugins/common/autoparagraph/lib",

		// Shortcuts for some often used extra plugins (not all)
		"cite":                         "bower_components/aloha-editor/src/plugins/extra/cite/lib",
		"cite/vendor":                  "bower_components/aloha-editor/src/plugins/extra/cite/vendor",
		"cite/css":                     "bower_components/aloha-editor/src/plugins/extra/cite/css",
		"cite/nls":                     "bower_components/aloha-editor/src/plugins/extra/cite/nls",
		"cite/res":                     "bower_components/aloha-editor/src/plugins/extra/cite/res",
		"numerated-headers":            "bower_components/aloha-editor/src/plugins/extra/numerated-headers/lib",
		"numerated-headers/vendor":     "bower_components/aloha-editor/src/plugins/extra/numerated-headers/vendor",
		"numerated-headers/css":        "bower_components/aloha-editor/src/plugins/extra/numerated-headers/css",
		"numerated-headers/nls":        "bower_components/aloha-editor/src/plugins/extra/numerated-headers/nls",
		"numerated-headers/res":        "bower_components/aloha-editor/src/plugins/extra/numerated-headers/res",
		"formatlesspaste":              "bower_components/aloha-editor/src/plugins/extra/formatlesspaste/lib",
		"formatlesspaste/vendor":       "bower_components/aloha-editor/src/plugins/extra/formatlesspaste/vendor",
		"formatlesspaste/css":          "bower_components/aloha-editor/src/plugins/extra/formatlesspaste/css",
		"formatlesspaste/nls":          "bower_components/aloha-editor/src/plugins/extra/formatlesspaste/nls",
		"formatlesspaste/res":          "bower_components/aloha-editor/src/plugins/extra/formatlesspaste/res",
		"linkbrowser":                  "bower_components/aloha-editor/src/plugins/extra/linkbrowser/lib",
		"linkbrowser/vendor":           "bower_components/aloha-editor/src/plugins/extra/linkbrowser/vendor",
		"linkbrowser/css":              "bower_components/aloha-editor/src/plugins/extra/linkbrowser/css",
		"linkbrowser/nls":              "bower_components/aloha-editor/src/plugins/extra/linkbrowser/nls",
		"linkbrowser/res":              "bower_components/aloha-editor/src/plugins/extra/linkbrowser/res",
		"imagebrowser":                 "bower_components/aloha-editor/src/plugins/extra/imagebrowser/lib",
		"imagebrowser/vendor":          "bower_components/aloha-editor/src/plugins/extra/imagebrowser/vendor",
		"imagebrowser/css":             "bower_components/aloha-editor/src/plugins/extra/imagebrowser/css",
		"imagebrowser/nls":             "bower_components/aloha-editor/src/plugins/extra/imagebrowser/nls",
		"imagebrowser/res":             "bower_components/aloha-editor/src/plugins/extra/imagebrowser/res",
		"ribbon":                       "bower_components/aloha-editor/src/plugins/extra/ribbon/lib",
		"ribbon/vendor":                "bower_components/aloha-editor/src/plugins/extra/ribbon/vendor",
		"ribbon/css":                   "bower_components/aloha-editor/src/plugins/extra/ribbon/css",
		"ribbon/nls":                   "bower_components/aloha-editor/src/plugins/extra/ribbon/nls",
		"ribbon/res":                   "bower_components/aloha-editor/src/plugins/extra/ribbon/res",
		"toc":                          "bower_components/aloha-editor/src/plugins/extra/toc/lib",
		"toc/vendor":                   "bower_components/aloha-editor/src/plugins/extra/toc/vendor",
		"toc/css":                      "bower_components/aloha-editor/src/plugins/extra/toc/css",
		"toc/nls":                      "bower_components/aloha-editor/src/plugins/extra/toc/nls",
		"toc/res":                      "bower_components/aloha-editor/src/plugins/extra/toc/res",
		"wai-lang":                     "bower_components/aloha-editor/src/plugins/extra/wai-lang/lib",
		"wai-lang/vendor":              "bower_components/aloha-editor/src/plugins/extra/wai-lang/vendor",
		"wai-lang/css":                 "bower_components/aloha-editor/src/plugins/extra/wai-lang/css",
		"wai-lang/nls":                 "bower_components/aloha-editor/src/plugins/extra/wai-lang/nls",
		"wai-lang/res":                 "bower_components/aloha-editor/src/plugins/extra/wai-lang/res",
		"headerids":                    "bower_components/aloha-editor/src/plugins/extra/headerids/lib",
		"headerids/vendor":             "bower_components/aloha-editor/src/plugins/extra/headerids/vendor",
		"headerids/css":                "bower_components/aloha-editor/src/plugins/extra/headerids/css",
		"headerids/nls":                "bower_components/aloha-editor/src/plugins/extra/headerids/nls",
		"headerids/res":                "bower_components/aloha-editor/src/plugins/extra/headerids/res",
		"metaview":                     "bower_components/aloha-editor/src/plugins/extra/metaview/lib",
		"metaview/vendor":              "bower_components/aloha-editor/src/plugins/extra/metaview/vendor",
		"metaview/css":                 "bower_components/aloha-editor/src/plugins/extra/metaview/css",
		"metaview/nls":                 "bower_components/aloha-editor/src/plugins/extra/metaview/nls",
		"metaview/res":                 "bower_components/aloha-editor/src/plugins/extra/metaview/res",
		"listenforcer":                 "bower_components/aloha-editor/src/plugins/extra/listenforcer/lib",
		"listenforcer/vendor":          "bower_components/aloha-editor/src/plugins/extra/listenforcer/vendor",
		"listenforcer/css":             "bower_components/aloha-editor/src/plugins/extra/listenforcer/css",
		"listenforcer/nls":             "bower_components/aloha-editor/src/plugins/extra/listenforcer/nls",
		"listenforcer/res":             "bower_components/aloha-editor/src/plugins/extra/listenforcer/res",

        // Aloha Plugins
        "ui/ui-plugin":                 "bower_components/aloha-editor/src/plugins/common/ui/lib/ui-plugin",
        "link-plugin":                  "bower_components/aloha-editor/src/lib/aloha/link/link-plugin",
        "table-plugin":                 "bower_components/aloha-editor/src/lib/aloha/table/table-plugin",
        "format-plugin":                "bower_components/aloha-editor/src/lib/aloha/format/format-plugin",
        "list-plugin":                  "bower_components/aloha-editor/src/lib/aloha/list/list-plugin",
        "image-plugin":                 "bower_components/aloha-editor/src/lib/aloha/image/image-plugin",
        "highlighteditables-plugin":    "bower_components/aloha-editor/src/lib/aloha/highlighteditables/highlighteditables-plugin",
        "dom-to-xhtml-plugin":          "bower_components/aloha-editor/src/lib/aloha/dom-to-xhtml/dom-to-xhtml-plugin",
        "contenthandler-plugin":        "bower_components/aloha-editor/src/lib/aloha/contenthandler/contenthandler-plugin",
        "characterpicker-plugin":       "bower_components/aloha-editor/src/lib/aloha/characterpicker/characterpicker-plugin",
        "commands-plugin":              "bower_components/aloha-editor/src/lib/aloha/commands/commands-plugin",
        "block-plugin":                 "bower_components/aloha-editor/src/lib/aloha/block/block-plugin",
        "align-plugin":                 "bower_components/aloha-editor/src/lib/aloha/align/align-plugin",
        "abbr-plugin":                  "bower_components/aloha-editor/src/lib/aloha/abbr/abbr-plugin",
        "horizontalruler-plugin":       "bower_components/aloha-editor/src/lib/aloha/horizontalruler/horizontalruler-plugin",
        "undo-plugin":                  "bower_components/aloha-editor/src/lib/aloha/undo/undo-plugin",
        "paste-plugin":                 "bower_components/aloha-editor/src/lib/aloha/paste/paste-plugin",
        "autoparagraph-plugin":         "bower_components/aloha-editor/src/lib/aloha/autoparagraph/autoparagraph-plugin",

        "i18n":                        "bower_components/aloha-editor/src/lib/i18n",
        "vendor":                        "bower_components/aloha-editor/src/lib/vendor",
        "aloha":                        "bower_components/aloha-editor/src/lib/aloha",
        "util":                         "bower_components/aloha-editor/src/lib/util"
    },
    "shim": {
        "logging": { "exports": "logging" },
    }
});

require(["pat-registry", "pat-editor"], function(registry, editor) {
    window.patterns = registry;
    registry.init();
});
